# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: flix-busDB
    ports:
      - 27017:27017
    networks:
      - flix_busnetwork
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - data:/data/db 
  
  agency:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: flix-bus 
    ports: 
      - 8080:8080
    networks:
      - flix_busnetwork
    restart: always
    depends_on: 
      - mongo 
    


volumes:
    data: 

networks:
    flix_busnetwork: 